-- psql -U $POSTGRES_USER $POSTGRES_DB
CREATE SCHEMA IF NOT EXISTS cafeteria;

CREATE TABLE cafeteria.icon (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  icon_name varchar(100) NOT NULL,
  bootstrap_name varchar(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE cafeteria.cafeteria_location (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  location_name varchar(100) NOT NULL,
  location_description varchar(200) NOT NULL,
  icon_id int4,
  printer_url varchar(500),
  PRIMARY KEY (id),
  FOREIGN KEY (icon_id) REFERENCES cafeteria.icon (id)
);

CREATE TABLE cafeteria.week_day (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  weekday_name varchar(20) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE cafeteria.location_business_hours (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  location_id int4 NOT NULL,
  weekday_id int4 NOT NULL,
  open_time time NOT NULL,
  close_time time NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (location_id) REFERENCES cafeteria.cafeteria_location (id),
  FOREIGN KEY (weekday_id) REFERENCES cafeteria.week_day (id)
);

CREATE TABLE cafeteria.location_exception_hours (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  location_id int4 NOT NULL,
  start_exception_datetime timestamp NOT NULL,
  end_exception_datetime timestamp NOT NULL,
  reason varchar(255),
  PRIMARY KEY (id),
  FOREIGN KEY (location_id) REFERENCES cafeteria.cafeteria_location (id)
);

CREATE TABLE cafeteria.station (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  location_id int4 NOT NULL,
  station_name varchar(50) NOT NULL,
  station_description varchar(200) NOT NULL,
  icon_id int4,
  PRIMARY KEY (id),
  FOREIGN KEY (location_id) REFERENCES cafeteria.cafeteria_location (id),
  FOREIGN KEY (icon_id) REFERENCES cafeteria.icon (id)
);

CREATE TABLE cafeteria.station_business_hours (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  station_id int4 NOT NULL,
  weekday_id int4 NOT NULL,
  open_time time NOT NULL,
  close_time time NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (station_id) REFERENCES cafeteria.station (id),
  FOREIGN KEY (weekday_id) REFERENCES cafeteria.week_day (id)
);

CREATE TABLE cafeteria.station_exception_hours (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  station_id int4 NOT NULL,
  start_exception_datetime timestamp NOT NULL,
  end_exception_datetime timestamp NOT NULL,
  reason varchar(255),
  PRIMARY KEY (id),
  FOREIGN KEY (station_id) REFERENCES cafeteria.station (id)
);

CREATE TABLE cafeteria.entree (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  station_id int4 NOT NULL,
  entree_name varchar(100) NOT NULL,
  entree_description varchar(200),
  entree_price decimal NOT NULL,
  image_url varchar(500),
  in_stock boolean NOT NULL DEFAULT true,
  PRIMARY KEY (id),
  FOREIGN KEY (station_id) REFERENCES cafeteria.station (id)
);

CREATE TABLE cafeteria.side (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  station_id int4 NOT NULL,
  side_name varchar(100) NOT NULL,
  side_description varchar(200),
  side_price decimal NOT NULL,
  image_url varchar(500),
  in_stock boolean NOT NULL DEFAULT true,
  PRIMARY KEY (id),
  FOREIGN KEY (station_id) REFERENCES cafeteria.station (id)
);

CREATE TABLE cafeteria.drink (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  location_id int4 NOT NULL,
  drink_name varchar(100) NOT NULL,
  drink_description varchar(200),
  drink_price decimal NOT NULL,
  image_url varchar(500),
  in_stock boolean NOT NULL DEFAULT true,
  PRIMARY KEY (id),
  FOREIGN KEY (location_id) REFERENCES cafeteria.cafeteria_location (id)
);

CREATE TABLE cafeteria.meal (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  entree_id int4 NOT NULL,
  side_id int4,
  drink_id int4 NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (entree_id) REFERENCES cafeteria.entree (id),
  FOREIGN KEY (side_id) REFERENCES cafeteria.side (id),
  FOREIGN KEY (drink_id) REFERENCES cafeteria.drink (id)
);

CREATE TABLE cafeteria.food_option_type (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  food_option_type_name varchar(50) NOT NULL,
  required_amount int4 NOT NULL,
  included_amount int4 NOT NULL,
  max_amount int4 NOT NULL,
  food_option_price decimal NOT NULL,
  entree_id int4,
  side_id int4,
  icon_id int4,
  PRIMARY KEY (id),
  FOREIGN KEY (entree_id) REFERENCES cafeteria.entree (id),
  FOREIGN KEY (side_id) REFERENCES cafeteria.side (id),
  FOREIGN KEY (icon_id) REFERENCES cafeteria.icon (id)
);

CREATE TABLE cafeteria.food_option (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  food_option_name varchar(100) NOT NULL,
  in_stock boolean NOT NULL DEFAULT true,
  image_url varchar(500),
  PRIMARY KEY (id)
);

CREATE TABLE cafeteria.option_option_type (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  food_option_id int4 NOT NULL,
  food_option_type_id int4 NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (food_option_id) REFERENCES cafeteria.food_option (id),
  FOREIGN KEY (food_option_type_id) REFERENCES cafeteria.food_option_type (id)
);

CREATE TABLE cafeteria.customer (
  badger_id int4 UNIQUE GENERATED BY DEFAULT AS IDENTITY,
  email varchar(100) UNIQUE NOT NULL,
  cust_name varchar(100) NOT NULL,
  user_role varchar(20) CHECK (user_role IN ('admin', 'food-service') OR user_role IS NULL),
  primary key (email)
);

CREATE TABLE cafeteria.customer_swipe (
  badger_id int NOT NULL,
  swipe_balance int4 NOT NULL,
  end_date timestamp
);

CREATE TABLE cafeteria.order (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  customer_badger_id int NOT NULL,
  order_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  total_price decimal,
  tax decimal NOT NULL DEFAULT 0,
  total_swipe int4,
  PRIMARY KEY (id),
  FOREIGN KEY (customer_badger_id) REFERENCES cafeteria.customer (badger_id)
);

CREATE TABLE cafeteria.sale_card (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  order_id int4 NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (order_id) REFERENCES cafeteria.order (id)
);

CREATE TABLE cafeteria.sale_swipe (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  order_id int4 NOT NULL,
  PRIMARY KEY (id),
  FOREIGN KEY (order_id) REFERENCES cafeteria.order (id)
);

CREATE TABLE cafeteria.food_item (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  name varchar(300) NOT NULL,
  order_id int4 NOT NULL,
  location_id int4,
  station_id int4,
  sale_card_id int4, -- fk to sale_card if paid by card nullable
  sale_swipe_id int4, -- fk to sale_swipe if paid by swipe nullable   
  swipe_cost int4,
  card_cost decimal,
  special boolean NOT NULL DEFAULT false,
  PRIMARY KEY (id),
  FOREIGN KEY (order_id) REFERENCES cafeteria.order (id),
  FOREIGN KEY (location_id) REFERENCES cafeteria.cafeteria_location (id),
  FOREIGN KEY (station_id) REFERENCES cafeteria.station (id),
  FOREIGN KEY (sale_card_id) REFERENCES cafeteria.sale_card (id),
  FOREIGN KEY (sale_swipe_id) REFERENCES cafeteria.sale_swipe (id)
);

CREATE TABLE cafeteria.food_item_option (
  id int4 GENERATED BY DEFAULT AS IDENTITY,
  food_item_order_id int4 NOT NULL,
  food_option_name varchar(100),
  PRIMARY KEY (id),
  FOREIGN KEY (food_item_order_id) REFERENCES cafeteria.food_item (id)
);






INSERT INTO
  cafeteria.icon (icon_name, bootstrap_name)
VALUES
  ('Location Pin', 'bi-geo-alt-fill'),
  ('Location Pin (outline)', 'bi-geo-alt'),
  ('Pin Map', 'bi-pin-map-fill'),
  ('Pin Map (outline)', 'bi-pin-map'),
  ('House Door', 'bi-house-door-fill'),
  ('House', 'bi-house-fill'),
  ('Building', 'bi-building-fill'),
  ('Building (outline)', 'bi-building'),
  ('Shop', 'bi-shop'),
  ('Shop Window', 'bi-shop-window'),
  ('Fire / Grill', 'bi-fire'),
  ('Hot Drink', 'bi-cup-hot-fill'),
  ('Hot Drink (outline)', 'bi-cup-hot'),
  ('Cup with Straw', 'bi-cup-straw'),
  ('Cup', 'bi-cup-fill'),
  ('Cup (outline)', 'bi-cup'),
  ('Fried Egg / Deli', 'bi-egg-fried'),
  ('Egg', 'bi-egg-fill'),
  ('Pie / Pizza', 'bi-pie-chart-fill'),
  ('Pie Chart (outline)', 'bi-pie-chart'),
  ('Tornado / Wraps', 'bi-tornado'),
  ('Basket', 'bi-basket-fill'),
  ('Basket 2', 'bi-basket2-fill'),
  ('Cart', 'bi-cart-fill'),
  ('Bag', 'bi-bag-fill'),
  ('Bag Heart', 'bi-bag-heart-fill'),
  ('People', 'bi-people-fill'),
  ('Person', 'bi-person-fill'),
  ('Person Circle', 'bi-person-circle'),
  ('Book', 'bi-book-fill'),
  ('Book (outline)', 'bi-book'),
  ('Star', 'bi-star-fill'),
  ('Heart', 'bi-heart-fill'),
  ('Lightning', 'bi-lightning-fill'),
  ('Sun', 'bi-sun-fill'),
  ('Moon', 'bi-moon-fill'),
  ('Circle', 'bi-circle-fill'),
  ('Diamond', 'bi-diamond-fill'),
  ('Trophy', 'bi-trophy-fill'),
  ('Award', 'bi-award-fill'),
  ('Flower', 'bi-flower1'),
  ('Flower 2', 'bi-flower2'),
  ('Tree', 'bi-tree-fill'),
  ('Bell', 'bi-bell-fill'),
  ('Clock', 'bi-clock-fill'),
  ('Calendar', 'bi-calendar-fill'),
  ('Tag', 'bi-tag-fill'),
  ('Grid', 'bi-grid-fill'),
  ('List', 'bi-list'),
  ('Info', 'bi-info-circle-fill');

INSERT INTO
  cafeteria.cafeteria_location (
    location_name,
    location_description,
    icon_id,
    printer_url
  )
VALUES
  (
    'Badger Den',
    'Located on the main floor of the Greenwood Student Center',
    5,
    'http://cafeteria-2:8000'
  ),
  (
    'Busters Bistro',
    'Located on the main floor of the Karen H Huntsman Library',
    30,
    'http://cafeteria-3:8000'
  );

INSERT INTO
  cafeteria.week_day (weekday_name)
VALUES
  ('Monday'),
  ('Tuesday'),
  ('Wednesday'),
  ('Thursday'),
  ('Friday'),
  ('Saturday'),
  ('Sunday');

INSERT INTO
  cafeteria.location_business_hours (location_id, weekday_id, open_time, close_time)
VALUES
  -- Badger Den hours (Mon-Fri)
  (1, 1, '08:00:00', '19:30:00'),
  (1, 2, '08:00:00', '19:30:00'),
  (1, 3, '08:00:00', '19:30:00'),
  (1, 4, '08:00:00', '19:30:00'),
  (1, 5, '08:00:00', '19:30:00'),
  -- Badger Den Weekend hours (Sat-Sun)
  (1, 6, '17:00:00', '19:00:00'),
  (1, 7, '17:00:00', '19:00:00'),
  -- Busters Bistro hours (Mon-Fri)
  (2, 1, '10:00:00', '19:30:00'),
  (2, 2, '10:00:00', '19:30:00'),
  (2, 3, '10:00:00', '19:30:00'),
  (2, 4, '10:00:00', '19:30:00'),
  (2, 5, '10:00:00', '15:00:00');

INSERT INTO
  cafeteria.station (
    location_id,
    station_name,
    station_description,
    icon_id
  )
VALUES
  (
    1,
    'Breakfast',
    'Hot breakfast entrees and sides',
    12
  ),
  (1, 'Deli', 'Fresh made-to-order sandwiches', 17),
  (1, 'Grill', 'Hot entrees and burgers', 11),
  (
    1,
    'Pizza',
    'Fresh pizza with your choice of toppings',
    37
  ),
  (2, 'Wraps', 'Fresh wraps and healthy options', 21);

INSERT INTO
  cafeteria.station_business_hours (station_id, weekday_id, open_time, close_time)
VALUES
  -- Breakfast hours (Mon-Fri)
  (1, 1, '08:00:00', '11:00:00'),
  (1, 2, '08:00:00', '11:00:00'),
  (1, 3, '08:00:00', '11:00:00'),
  (1, 4, '08:00:00', '11:00:00'),
  (1, 5, '08:00:00', '11:00:00'),
  -- Deli Weekday hours (Mon-Fri)
  (2, 1, '11:00:00', '19:30:00'),
  (2, 2, '11:00:00', '19:30:00'),
  (2, 3, '11:00:00', '19:30:00'),
  (2, 4, '11:00:00', '19:30:00'),
  (2, 5, '11:00:00', '19:30:00'),
  -- Deli Weekend hours (Sat-Sun)
  (2, 6, '17:00:00', '19:00:00'),
  (2, 7, '17:00:00', '19:00:00'),
  -- Grill Lunch/Dinner hours (Mon-Fri)
  (3, 1, '11:00:00', '19:30:00'),
  (3, 2, '11:00:00', '19:30:00'),
  (3, 3, '11:00:00', '19:30:00'),
  (3, 4, '11:00:00', '19:30:00'),
  (3, 5, '11:00:00', '19:30:00'),
  -- Grill Weekend hours (Sat-Sun)
  (3, 6, '17:00:00', '19:00:00'),
  (3, 7, '17:00:00', '19:00:00'),
  -- Pizza Weekday hours (Mon-Fri)
  (4, 1, '11:00:00', '19:30:00'),
  (4, 2, '11:00:00', '19:30:00'),
  (4, 3, '11:00:00', '19:30:00'),
  (4, 4, '11:00:00', '19:30:00'),
  (4, 5, '11:00:00', '19:30:00'),
  -- Pizza Weekend hours (Sat-Sun)
  (4, 6, '17:00:00', '19:00:00'),
  (4, 7, '17:00:00', '19:00:00'),
  -- Wraps hours (Mon-Fri)
  (5, 1, '10:00:00', '19:30:00'),
  (5, 2, '10:00:00', '19:30:00'),
  (5, 3, '10:00:00', '19:30:00'),
  (5, 4, '10:00:00', '19:30:00'),
  (5, 5, '10:00:00', '15:00:00');

INSERT INTO
  cafeteria.entree (
    station_id,
    entree_name,
    entree_description,
    entree_price
  )
VALUES
-- Breakfast Station Entrees
  (
    1,
    'Breakfast Burrito',
    'Scrambled eggs, potatoes, and cheese wrapped in a warm tortilla',
    4.99,
  ),
  (
    1, -- Id 2 needs meat option types configured
    'Breakfast Burrito With Meat',
    'Scrambled eggs, potatoes, cheese, and your choice of meat wrapped in a warm tortilla',
    5.99,
  ),
  (
    1, -- Id 3 needs bread options configured
    'Breakfast Sandwich Muffin / Biscuit',
    'Scrambled eggs and cheese on a toasted English muffin or biscuit',
    3.49,
  ),
  (
    1, -- Id 4 needs bread and meat options configured
    'Breakfast Sandwich Muffin / Biscuit With Meat',
    'Scrambled eggs, cheese and your choice of meat on a toasted English muffin or biscuit',
    4.19,
  ),
  (
    1, -- Id 5 needs bread options configured
    'Breakfast Sandwich Bagel / Croissant',
    'Scrambled eggs and cheese on a toasted English muffin or biscuit',
    4.29,
  ),
  (
    1, -- Id 6 needs bread and meat options configured
    'Breakfast Sandwich Bagel / Croissant With Meat',
    'Scrambled eggs, cheese and your choice of meat on a toasted English muffin or biscuit',
    4.89,
  ),
  (
    1, -- Id 7 needs plate base and meat options configured
    'Breakfast Plate',
    'Breakfast sides including eggs, toast, potatoes, and your choice of meat',
    4.29,
  ),
  (
    1, 
    'Cheese Omelet',
    'Made to order omelet with your choice of cheese',
    3.89,
  ),
  (
    1, -- Id 9 needs meat options configured
    'Omelet with meat',
    'Made to order omelet with your choice of meat and cheese',
    5.19,
  ),
  (
    1, -- Id 10 needs meat options configured
    'Omelet combo',
    'Made to order omelet with only cheese and eggs, with a side of hashbrowns and toast',
    5.99,
  ),
  (1, 
    'French Toast',
    'Crispy golden French toast',
    3.29,
  ),
  (1, 
    '1 Pancake',
    'Single large crispy pancake',
    2.49, -- NOTE Not on screen 
  ),
  (1, 
    '2 Pancakes',
    'Two large crispy pancakes',
    3.99,
  ),
  (1, 
    'Biscuits and Gravy',
    'Crispy biscuits with savory gravy',
    4.89,
  ),

-- Deli Station Entrees
  (
    2, -- Id 15 needs bread, meat, cheese, toppings, and dressing options configured
    'Deli Sandwich',
    'A sandwich with your choice of meat, cheese, toppings, and dressing',
    5.99,
  )

  -- (
  --   3,
  --   'Chicken Quesadilla',
  --   'Grilled chicken and cheese in a warm tortilla',
  --   5.29,
  -- ),
  -- (
  --   3,
  --   'Steak Quesadilla',
  --   'Grilled steak and cheese in a warm tortilla',
  --   5.49,
  -- ),
  -- (
  --   3,
  --   'Cheese Quesadilla',
  --   'Grilled cheese in a warm tortilla',
  --   3.99,
  -- ),
  -- (
  --   4,
  --   'Two Toppings Pizza',
  --   'Small pizza with two toppings',
  --   5.69,
  -- ),
  -- (
  --   2,
  --   'Deli Sandwich',
  --   'A sandwich with your choice of meat, cheese, toppings, and dressing',
  --   6.79,
  -- ),
  -- (
  --   5,
  --   'Custom Wrap',
  --   'Fresh wrap with your choice of fillings',
  --   5.69,
  -- );

INSERT INTO
  cafeteria.side (
    station_id,
    side_name,
    side_description,
    side_price
  )
VALUES
-- Breakfast Sides
  (
    1,
    'Hashbrowns',
    'Crispy golden hashbrowns',
    1.99,
  ),
  (
    1,
    'Toast',
    'Crispy golden toast, made from a thick slice of white bread',
    1.49,
  ),
  (
    1,
    'Sausage Patty',
    'Crispy sausage patty',
    1.49,
  ),
  (
    1,
    'Bacon',
    'Several strips of crispy bacon',
    1.49,
  ),
  (
    1,
    'Ham',
    'A slice of savory ham',
    1.49,
  ),
-- Deli Station Sides
  (
    2,
    'Chips',
    'Your choice of crispy chips from the selection on the shelf',
    0.89,
  ),
  -- (
  --   3,
  --   'Rice',
  --   'Steamed white rice',
  --   1.79,
  -- ),
  -- (
  --   3,
  --   'Vegetables',
  --   'Steamed mixed vegetables',
  --   1.79,
  -- ),
  -- (
  --   3,
  --   'Waffle Fries',
  --   'Crispy golden waffle fries',
  --   2.29,
  -- ),
  -- (
  --   5,
  --   'Side Salad',
  --   'Fresh side salad with mixed greens and vegetables',
  --   2.29,
  -- ),
  -- (
  --   5,
  --   'Fruit Cup',
  --   'Fresh fruit cup with a variety of seasonal fruits',
  --   2.29,
  -- ),
  -- (
  --   4,
  --   'Chips',
  --   'Crispy chips',
  --   0.89,
  -- );

INSERT INTO
  cafeteria.drink (
    location_id,
    drink_name,
    drink_description,
    drink_price
  )
VALUES
  (
    1,
    'Slushies',
    'Assorted flavors of icy slushies',
    1.49,
  ),
  (
    1,
    'Fountain Soda',
    'Coca-cola products, and other fountain drinks of your choice',
    1.49,
  ),
  (
    1,
    'Tea/Coffee Machine',
    'Freshly brewed iced tea',
    1.49,
  )
  (
    2,
    'Bottled Drinks',
    'Assorted bottled drinks including select water, juice, and soda',
    1.49,
  );

INSERT INTO
  cafeteria.food_option (food_option_name, in_stock)
VALUES
  -- Meat Options
  ("Sausage", true),-- id = 1
  ("Ham", true),-- id = 2
  ("Bacon", true),-- id = 3

  -- Bread Options
  ("Croissant", true), -- id = 
  ("English Muffin", true), -- id = 
  ("Biscuit", true), -- id = 
  ("Bagel", true), -- id = 

  -- Cheese Options
  ("American", true), -- id = 
  ("Cheddar", true), -- id = 
  ("Pepper Jack", true), -- id = 
  ("Swiss", true), -- id = 
  ("", true), -- id = 
  ("", true), -- id = 
  ("", true), -- id = 


  -- Topping/inclusion options
  ("Bell Peppers", true), -- id = 
  ("Potatoes", true), -- id =
  ("Onions", true), -- id = 
  ("Mushrooms", true), -- id = 
  ("", true), -- id = 
  ("", true), -- id = 
  ("", true), -- id = 


  -- Egg Options
  ("Scrambled", true), -- id = 
  ("Over Easy", false), -- id = 
  ("Over Hard", true), -- id =
  ("Sunny Side Up", false), -- id = 

  ();

INSERT INTO
  cafeteria.food_option_type (
    food_option_type_name,
    required_amount,
    included_amount,
    max_amount,
    food_option_price,
    entree_id,
    side_id
  )
VALUES
  -- Breakfast Burrito with Meat options (entree_id 2)
  ('Meat', 1, 1, 1, 0.00, 2, NULL), -- id=1:  must pick exactly 1 meat option for the burrito

  -- Breakfast Sandwich Muffing/Biscuit options (entree_id 3)
  ('Bread', 1, 1, 1, 0.00, 3, NULL), -- id=2:  pick exactly 1 bread option for the sandwich
  ('Cheese', 1, 1, 1, 0.00, 3, NULL), -- id=3:  pick exactly 1 cheese option for the sandwich

  -- Breakfast Sandwich Muffing/Biscuit with Meat options (entree_id 4)
  ('Bread', 1, 1, 1, 0.00, 4, NULL), -- id=4:  pick exactly 1 bread option for the sandwich
  ('Cheese', 1, 1, 1, 0.00, 4, NULL), -- id=5:  pick exactly 1 cheese option for the sandwich
  ('Meat', 1, 1, 1, 0.00, 4, NULL), -- id=6:  pick exactly 1 meat option for the sandwich, extra charge applies

  -- Breakfast Sandwich Bagel/Croissant options (entree_id 5)
  ('Bread', 1, 1, 1, 0.00, 5, NULL), -- id=7:  pick exactly 1 bread option for the sandwich
  ('Cheese', 1, 1, 1, 0.00, 5, NULL), -- id=8:  pick exactly 1 cheese option for the sandwich

  -- Breakfast Sandwich Bagel/Croissant with Meat options (entree_id 6)
  ('Bread', 1, 1, 1, 0.00, 6, NULL), -- id=9:  pick exactly 1 bread option for the sandwich
  ('Cheese', 1, 1, 1, 0.00, 6, NULL), -- id=10: pick exactly 1 cheese option for the sandwich
  ('Meat', 1, 1, 1, 0.00, 6, NULL), -- id=11: pick exactly 1 meat option for the sandwich, extra charge applies

  -- Breakfast Plate options (entree_id 7)
  ('Meat', 1, 1, 1, 0.00, 7, NULL), -- id=12: must pick exactly 1 meat option for the plate
  ('Eggs', 1, 1, 1, 0.00, 7, NULL); -- id=13: must pick exactly 1 egg option for the plate

  -- -- Breakfast Plate options (entree_id 3)
  -- ('Plate Base', 1, 1, 1, 0.00, 3, NULL), -- id=1:  pick exactly 1
  -- ('Meat Choice', 1, 1, 1, 0.00, 3, NULL), -- id=2:  pick exactly 1
  -- -- Two Toppings Pizza (entree_id 7)
  -- ('Toppings', 2, 2, 12, 0.89, 7, NULL), -- id=3:  must pick 2, first 2 free, up to 12
  -- -- Deli sandwich (entree_id 8)
  -- ('Bread', 1, 1, 1, 0.00, 8, NULL), -- id=4:  pick exactly 1
  -- ('Meat', 1, 1, 1, 0.75, 8, NULL), -- id=5:  pick exactly 1 (extra charge applies)
  -- ('Cheese', 1, 1, 1, 0.00, 8, NULL), -- id=6:  pick exactly 1
  -- ('Toppings', 0, 3, 10, 0.50, 8, NULL), -- id=7:  optional, first 3 free, up to 10
  -- ('Dressing', 1, 1, 1, 0.00, 8, NULL), -- id=8:  pick exactly 1
  -- -- Custom Wrap (entree_id 9)
  -- ('Tortilla', 1, 1, 1, 0.00, 9, NULL), -- id=9:  pick exactly 1
  -- ('Protein', 1, 1, 2, 1.50, 9, NULL), -- id=10: must pick 1, can add a 2nd for $1.50
  -- ('Fillings', 3, 3, 8, 0.50, 9, NULL);

-- id=11: must pick 3, first 3 free, up to 8
INSERT INTO
  cafeteria.option_option_type (food_option_id, food_option_type_id)
VALUES
-- Breakfast Options
  (1, 1), -- Sausage -> Breakfast Burrito with Meat
  (2, 1), -- Ham -> Breakfast Burrito with Meat
  (3, 1), -- Bacon -> Breakfast Burrito with Meat

  (4, 2), -- Croissant -> Breakfast Sandwich Muffin/Biscuit
  (5, 2), -- English Muffin -> Breakfast Sandwich Muffin/Biscuit
  (6, 2), -- Biscuit -> Breakfast Sandwich Muffin/Biscuit
  (7, 2), -- Bagel -> Breakfast Sandwich Muffin/Biscuit

  (4, 3), -- Croissant -> Breakfast Sandwich Muffin/Biscuit with Meat
  (5, 3), -- English Muffin -> Breakfast Sandwich Muffin/Biscuit with Meat
  (6, 3), -- Biscuit -> Breakfast Sandwich Muffin/Biscuit with Meat
  (7, 3), -- Bagel -> Breakfast Sandwich Muffin/Biscuit with Meat
  (1, 6), -- Sausage -> Breakfast Sandwich Muffin/Biscuit with Meat
  (2, 6), -- Ham -> Breakfast Sandwich Muffin/Biscuit with Meat
  (3, 6); -- Bacon -> Breakfast Sandwich Muffin/Biscuit with Meat

-- Jalapenos -> Fillings
-- Sample customer data
INSERT INTO
  cafeteria.customer (email, badger_id, cust_name, user_role)
VALUES
  ('john.doe@snow.edu', 1001234, 'John Doe', NULL),
  ('jane.smith@snow.edu', 1005678, 'Jane Smith', NULL),
  ('bob.johnson@snow.edu', 1009012, 'Bob Johnson', NULL),
  ('alice.williams@snow.edu', 1003456, 'Alice Williams', NULL),
  ('charlie.brown@snow.edu', 1007890, 'Charlie Brown', NULL),
  ('test-1@example.com', 1000001, 'Test1 User', NULL),
  ('test-2@example.com', 1000002, 'Test2 User', 'food-service'),
  ('test-3@example.com', 1000003, 'Test3 User', NULL),
  ('admin@example.com', 1000004, 'Admin User', 'admin');

-- Sample customer swipe data
INSERT INTO
  cafeteria.customer_swipe (badger_id, swipe_balance, end_date)
VALUES
  (1001234, 7, '2024-12-31 23:59:59'),
  (1005678, 21, '2026-12-31 23:59:59'),
  (1009012, 8, '2024-12-31 23:59:59'),
  (1003456, 9, '2026-12-31 23:59:59'),
  (1007890, 0, '2027-12-31 23:59:59'),
  (1000001, 5, '2028-12-31 23:59:59'),
  (1000002, 2, '2026-2-28 23:59:59');
