CREATE SCHEMA IF NOT EXISTS cafeteria;

CREATE TABLE IF NOT EXISTS cafeteria.test_table (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
