apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeteria-api-server-dep
  namespace: cafeteria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafeteria-api

  template:
    metadata:
      labels:
        app: cafeteria-api
    spec:
      containers:
        - name: cafeteria-api-container
          image: tjwalkr3/cafeteria-api:$CONTAINER_VERSION
          env:
            - name: ConnectionStrings__cafeteria
              value: "Host=cafeteria-db-svc;Port=5432;Database=cafeteriadb;Username=cafeteria_user;Password=cafeteria_password"
            - name: Keycloak__Authority
              value: "http://cafeteria-keycloak-svc:8080/realms/AppRealm"
            - name: Keycloak__Audience
              value: "cafeteria"
            - name: TZ
              value: "America/Denver"
          ports:
            - containerPort: 8080
        - name: tailscale-sidecar
          image: tailscale/tailscale:stable
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
                - NET_RAW
          env:
            - name: TS_AUTHKEY
              valueFrom:
                secretKeyRef:
                  name: tailscale-auth
                  key: TS_AUTHKEY
            - name: TS_KUBE_SECRET
              value: ""
            - name: TS_STATE_DIR
              value: /var/lib/tailscale
            - name: TS_USERSPACE
              value: "false"
            - name: TS_ACCEPT_DNS
              value: "false"
            - name: TS_EXTRA_ARGS
              value: "--accept-routes --reset"
          volumeMounts:
            - name: tailscale-state
              mountPath: /var/lib/tailscale
            - name: dev-net-tun
              mountPath: /dev/net/tun
      volumes:
        - name: tailscale-state
          emptyDir: {}
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice

---
apiVersion: v1
kind: Service
metadata:
  name: cafeteria-api-svc
  namespace: cafeteria
spec:
  selector:
    app: cafeteria-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
