apiVersion: apps/v1
kind: Deployment
metadata:
  name: cafeteria-db-dep
  namespace: cafeteria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cafeteria-db

  template:
    metadata:
      labels:
        app: cafeteria-db
    spec: 
      volumes:
      - name: schema-init
        configMap:
          name: cafeteria-db-init-sql
      containers:
      - name: cafeteria-postgres
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d/init.sql
          subPath: init.sql
          name: schema-init
        image: postgres:18-alpine3.22
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: "cafeteria_user"
        - name: POSTGRES_PASSWORD
          value: "cafeteria_password"
        - name: POSTGRES_DB
          value: "cafeteriadb"

---

apiVersion: v1
kind: Service
metadata:
  name: ham-exam-db-svc
  namespace: ham-exam
spec:
  selector:
    app: ham-exam-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: cafeteria-db-init-sql
  namespace: cafeteria
data:
  init.sql: |
    -- psql -U $POSTGRES_USER $POSTGRES_DB
    CREATE SCHEMA IF NOT EXISTS cafeteria;

    CREATE TABLE
        cafeteria.cafeteria_location (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            location_name varchar(100) NOT NULL,
            location_description varchar(200) NOT NULL,
            image_url varchar(500),
            PRIMARY KEY (id)
        );

    CREATE TABLE
        cafeteria.week_day (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            weekday_name varchar(20) NOT NULL,
            PRIMARY KEY (id)
        );

    CREATE TABLE
        cafeteria.location_business_hours (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            location_id int4 NOT NULL,
            weekday_id int4 NOT NULL,
            open_time time NOT NULL,
            close_time time NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY (location_id) REFERENCES cafeteria.cafeteria_location (id),
            FOREIGN KEY (weekday_id) REFERENCES cafeteria.week_day (id)
        );


    CREATE TABLE
        cafeteria.station (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            location_id int4 NOT NULL,
            station_name varchar(50) NOT NULL,
            station_description varchar(200) NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY (location_id) REFERENCES cafeteria.cafeteria_location (id)
        );

    CREATE TABLE
        cafeteria.entree (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            station_id int4 NOT NULL,
            entree_name varchar(100) NOT NULL,
            entree_description varchar(200),
            entree_price decimal NOT NULL,
            image_url varchar(500),
            PRIMARY KEY (id),
            FOREIGN KEY (station_id) REFERENCES cafeteria.station (id)
        );

    CREATE TABLE
        cafeteria.side (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            station_id int4 NOT NULL,
            side_name varchar(100) NOT NULL,
            side_description varchar(200),
            side_price decimal NOT NULL,
            image_url varchar(500),
            PRIMARY KEY (id),
            FOREIGN KEY (station_id) REFERENCES cafeteria.station (id)
        );

    CREATE TABLE
        cafeteria.drink (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            station_id int4 NOT NULL,
            drink_name varchar(100) NOT NULL,
            drink_description varchar(200),
            drink_price decimal NOT NULL,
            image_url varchar(500),
            PRIMARY KEY (id),
            FOREIGN KEY (station_id) REFERENCES cafeteria.station (id)
        );

    CREATE TABLE
        cafeteria.meal (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            entree_id int4 NOT NULL,
            side_id int4,
            drink_id int4 NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY (entree_id) REFERENCES cafeteria.entree (id),
            FOREIGN KEY (side_id) REFERENCES cafeteria.side (id),
            FOREIGN KEY (drink_id) REFERENCES cafeteria.drink (id)
        );

    CREATE TABLE
        cafeteria.food_option_type (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            food_option_type_name varchar(50) NOT NULL,
            num_included int2 NOT NULL,
            max_amount int4 NOT NULL,
            food_option_price decimal NOT NULL,
            entree_id int4,
            side_id int4,
            PRIMARY KEY (id)
        );

    CREATE TABLE
        cafeteria.food_option (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            food_option_name varchar(100) NOT NULL,
            in_stock boolean NOT NULL DEFAULT true,
            image_url varchar(500),
            PRIMARY KEY (id)
        );

    CREATE TABLE
        cafeteria.option_option_type (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            food_option_id int4 NOT NULL,
            food_option_type_id int4 NOT NULL,
            PRIMARY KEY (id)
        );

    INSERT INTO cafeteria.cafeteria_location (location_name, location_description, image_url) VALUES
        ('Badger Den', 'Located on the main floor of the Greenwood Student Center', 'https://picsum.photos/id/292/300/200'),
        ('Busters Bistro', 'Located on the main floor of the Karen H Huntsman Library', 'https://picsum.photos/id/326/300/200');

    INSERT INTO cafeteria.week_day (weekday_name) VALUES
        ('Monday'),
        ('Tuesday'),
        ('Wednesday'),
        ('Thursday'),
        ('Friday'),
        ('Saturday'),
        ('Sunday');

    INSERT INTO cafeteria.location_business_hours (location_id, weekday_id, open_time, close_time) VALUES
        -- Badger Den Breakfast hours (Mon-Fri)
        (1, 1, '08:00:00', '11:00:00'),
        (1, 2, '08:00:00', '11:00:00'),
        (1, 3, '08:00:00', '11:00:00'),
        (1, 4, '08:00:00', '11:00:00'),
        (1, 5, '08:00:00', '11:00:00'),
        -- Badger Den Lunch/Dinner hours (Mon-Fri)
        (1, 1, '11:00:00', '19:30:00'),
        (1, 2, '11:00:00', '19:30:00'),
        (1, 3, '11:00:00', '19:30:00'),
        (1, 4, '11:00:00', '19:30:00'),
        (1, 5, '11:00:00', '19:30:00'),
        -- Badger Den Weekend hours (Sat-Sun)
        (1, 6, '17:00:00', '19:00:00'),
        (1, 7, '17:00:00', '19:00:00'),
        -- Busters Bistro hours (Mon-Fri)
        (2, 1, '10:00:00', '19:30:00'),
        (2, 2, '10:00:00', '19:30:00'),
        (2, 3, '10:00:00', '19:30:00'),
        (2, 4, '10:00:00', '19:30:00'),
        (2, 5, '10:00:00', '15:00:00');

    INSERT INTO cafeteria.station (location_id, station_name, station_description) VALUES
        (1, 'Breakfast', 'Hot breakfast entrees and sides'),
        (1, 'Deli', 'Fresh made-to-order sandwiches'),
        (1, 'Grill', 'Hot entrees and burgers'),
        (1, 'Pizza', 'Fresh pizza with your choice of toppings'),
        (2, 'Wraps', 'Fresh wraps and healthy options');

    INSERT INTO cafeteria.entree (station_id, entree_name, entree_description, entree_price, image_url) VALUES
        (1, 'Turkey Sandwich', 'Turkey sandwich with lettuce on wheat bread', 6.50, 'https://picsum.photos/id/488/150/150'),
        (3, 'Cheeseburger', 'Classic cheeseburger with lettuce and tomato', 7.95, 'https://picsum.photos/id/431/150/150');

    INSERT INTO cafeteria.side (station_id, side_name, side_description, side_price, image_url) VALUES
        (2, 'Garden Salad', 'Fresh green salad with lettuce and tomato', 4.95, 'https://picsum.photos/id/550/150/150'),
        (3, 'French Fries', 'Crispy golden french fries', 2.50, 'https://picsum.photos/id/225/150/150');

    INSERT INTO cafeteria.drink (station_id, drink_name, drink_description, drink_price, image_url) VALUES
        (1, 'Soda', 'Assorted soft drinks', 1.99, 'https://picsum.photos/id/163/150/150'),
        (2, 'Iced Tea', 'Freshly brewed iced tea', 1.99, 'https://picsum.photos/id/225/150/150'),
        (3, 'Water', 'Bottled water', 0.99, 'https://picsum.photos/id/1025/150/150');

    INSERT INTO cafeteria.meal (entree_id, side_id, drink_id) VALUES
        (1, 1, 1),
        (2, 2, 2);

    INSERT INTO cafeteria.food_option (food_option_name, in_stock, image_url) VALUES
        ('Wheat Bread', true, 'https://picsum.photos/id/98/150/150'),
        ('Sliced Turkey', true, 'https://picsum.photos/id/429/150/150'),
        ('Fresh Lettuce', true, 'https://picsum.photos/id/550/150/150'),
        ('Sliced Tomato', true, 'https://picsum.photos/id/189/150/150');

    INSERT INTO cafeteria.food_option_type (food_option_type_name, num_included, max_amount, food_option_price, entree_id, side_id) VALUES
        ('Bread', 1, 1, 0.00, 1, NULL),
        ('Meat', 1, 2, 0.00, 1, NULL),
        ('Vegetable', 2, 5, 0.25, 1, NULL);

    INSERT INTO cafeteria.option_option_type (food_option_id, food_option_type_id) VALUES
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 3);
