namespace Cafeteria.IntegrationTests.Api;

public static class DBSql
{
    public static readonly string SqlData = """
        CREATE SCHEMA IF NOT EXISTS cafeteria;

        CREATE TABLE
            cafeteria.cafeteria_location (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                location_name varchar(100) NOT NULL,
                location_description varchar(200) NOT NULL,
                image_url varchar(500),
                printer_url varchar(500),
                PRIMARY KEY (id)
            );

        CREATE TABLE
            cafeteria.week_day (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                weekday_name varchar(20) NOT NULL,
                PRIMARY KEY (id)
            );

        CREATE TABLE
            cafeteria.location_business_hours (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                location_id int4 NOT NULL,
                weekday_id int4 NOT NULL,
                open_time time NOT NULL,
                close_time time NOT NULL,
                PRIMARY KEY (id),
                FOREIGN KEY (location_id) REFERENCES cafeteria.cafeteria_location (id),
                FOREIGN KEY (weekday_id) REFERENCES cafeteria.week_day (id)
            );

        CREATE TABLE
            cafeteria.station (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                location_id int4 NOT NULL,
                station_name varchar(50) NOT NULL,
                station_description varchar(200) NOT NULL,
                PRIMARY KEY (id),
                FOREIGN KEY (location_id) REFERENCES cafeteria.cafeteria_location (id)
            );

        CREATE TABLE
            cafeteria.station_business_hours (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                station_id int4 NOT NULL,
                weekday_id int4 NOT NULL,
                open_time time NOT NULL,
                close_time time NOT NULL,
                PRIMARY KEY (id),
                FOREIGN KEY (station_id) REFERENCES cafeteria.station (id),
                FOREIGN KEY (weekday_id) REFERENCES cafeteria.week_day (id)
            );

        CREATE TABLE
            cafeteria.entree (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                station_id int4 NOT NULL,
                entree_name varchar(100) NOT NULL,
                entree_description varchar(200),
                entree_price decimal NOT NULL,
                image_url varchar(500),
                in_stock boolean NOT NULL DEFAULT true,
                PRIMARY KEY (id),
                FOREIGN KEY (station_id) REFERENCES cafeteria.station (id)
            );

        CREATE TABLE
            cafeteria.side (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                station_id int4 NOT NULL,
                side_name varchar(100) NOT NULL,
                side_description varchar(200),
                side_price decimal NOT NULL,
                image_url varchar(500),
                in_stock boolean NOT NULL DEFAULT true,
                PRIMARY KEY (id),
                FOREIGN KEY (station_id) REFERENCES cafeteria.station (id)
            );

        CREATE TABLE
            cafeteria.drink (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                location_id int4 NOT NULL,
                drink_name varchar(100) NOT NULL,
                drink_description varchar(200),
                drink_price decimal NOT NULL,
                image_url varchar(500),
                in_stock boolean NOT NULL DEFAULT true,
                PRIMARY KEY (id),
                FOREIGN KEY (location_id) REFERENCES cafeteria.cafeteria_location (id)
            );

        CREATE TABLE
            cafeteria.meal (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                entree_id int4 NOT NULL,
                side_id int4,
                drink_id int4 NOT NULL,
                PRIMARY KEY (id),
                FOREIGN KEY (entree_id) REFERENCES cafeteria.entree (id),
                FOREIGN KEY (side_id) REFERENCES cafeteria.side (id),
                FOREIGN KEY (drink_id) REFERENCES cafeteria.drink (id)
            );

        CREATE TABLE
            cafeteria.food_option_type (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                food_option_type_name varchar(50) NOT NULL,
                num_included int2 NOT NULL,
                max_amount int4 NOT NULL,
                food_option_price decimal NOT NULL,
                entree_id int4,
                side_id int4,
                PRIMARY KEY (id)
            );

        CREATE TABLE
            cafeteria.food_option (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                food_option_name varchar(100) NOT NULL,
                in_stock boolean NOT NULL DEFAULT true,
                image_url varchar(500),
                PRIMARY KEY (id)
            );

        CREATE TABLE
            cafeteria.option_option_type (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                food_option_id int4 NOT NULL,
                food_option_type_id int4 NOT NULL,
                PRIMARY KEY (id)
            );

            CREATE TABLE
            cafeteria.customer(
                email varchar(100) UNIQUE NOT NULL, 
                badger_id int UNIQUE NOT NULL,
                first_name varchar(50) NOT NULL,
                last_name varchar(50) NOT NULL,
                primary key (email)
            );

        CREATE TABLE
            cafeteria.customer_swipe (
                badger_id int NOT NULL,
                swipe_balance int4 NOT NULL
            );

        CREATE TABLE
            cafeteria.order (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                customer_badger_id int,
                order_time timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                total_price decimal,
                tax decimal NOT NULL DEFAULT 0,
                total_swipe int4,
                PRIMARY KEY (id),
                FOREIGN KEY (customer_badger_id) REFERENCES cafeteria.customer(badger_id)
            );

        CREATE TABLE
            cafeteria.sale_card (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                order_id int4 NOT NULL,
                PRIMARY KEY (id),
                FOREIGN KEY (order_id) REFERENCES cafeteria.order (id)
            );

        CREATE TABLE
            cafeteria.sale_swipe (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                order_id int4 NOT NULL,
                PRIMARY KEY (id),
                FOREIGN KEY (order_id) REFERENCES cafeteria.order (id)
            );

        CREATE TABLE
            cafeteria.food_item (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                name varchar(300) NOT NULL,
                order_id int4 NOT NULL,
                station_id int4 NOT NULL,
                sale_card_id int4, -- fk to sale_card if paid by card nullable
                sale_swipe_id int4, -- fk to sale_swipe if paid by swipe nullable   
                swipe_cost int4,
                card_cost decimal,
                special boolean NOT NULL DEFAULT false,
                PRIMARY KEY (id),
                FOREIGN KEY (order_id) REFERENCES cafeteria.order (id),
                FOREIGN KEY (station_id) REFERENCES cafeteria.station (id),
                FOREIGN KEY (sale_card_id) REFERENCES cafeteria.sale_card (id),
                FOREIGN KEY (sale_swipe_id) REFERENCES cafeteria.sale_swipe (id)
            );

        CREATE TABLE
            cafeteria.food_item_option (
                id int4 GENERATED BY DEFAULT AS IDENTITY,
                food_item_order_id int4 NOT NULL,
                food_option_name varchar(100),
                PRIMARY KEY (id),
                FOREIGN KEY (food_item_order_id) REFERENCES cafeteria.food_item (id)
            );
        """;

    // SQL with sample data pre-loaded for all tests to use
    public static readonly string SqlDataWithSampleData =
        SqlData
        + """

            -- Sample data loaded once for all tests
            -- Tests should use IDs 100+ for their own test data to avoid conflicts

            -- Locations (IDs 1-10 reserved for sample data)
            INSERT INTO cafeteria.cafeteria_location (id, location_name, location_description, image_url, printer_url)
            VALUES 
                (1, 'Badger Den', 'Located on the main floor of the Greenwood Student Center', 'https://picsum.photos/id/292/300/200', 'http://test.com:8080'),
                (2, 'Busters Bistro', 'Located on the main floor of the Karen H Huntsman Library', 'https://picsum.photos/id/326/300/200', 'http://test.com:8080'),
                (3, 'Test Location', 'For read-only tests', 'https://picsum.photos/id/100/300/200', 'http://test.com:8080');

            -- Stations (IDs 1-10 reserved for sample data)
            INSERT INTO cafeteria.station (id, location_id, station_name, station_description)
            VALUES
                (1, 1, 'Sandwich Station', 'Fresh made-to-order sandwiches'),
                (2, 1, 'Grill Station', 'Hot grilled items'),
                (3, 2, 'Pizza Station', 'Fresh pizza by the slice');

            -- Entrees (IDs 1-20 reserved for sample data)
            INSERT INTO cafeteria.entree (id, station_id, entree_name, entree_description, entree_price, image_url)
            VALUES
                (1, 1, 'Grilled Chicken', 'Juicy grilled chicken breast', 8.99, 'https://picsum.photos/id/1/300/200'),
                (2, 1, 'Burger', 'Classic beef burger', 7.99, 'https://picsum.photos/id/2/300/200'),
                (3, 2, 'Hot Dog', 'All-beef hot dog', 5.99, 'https://picsum.photos/id/10/300/200');

            -- Sides (IDs 1-20 reserved for sample data)
            INSERT INTO cafeteria.side (id, station_id, side_name, side_description, side_price, image_url)
            VALUES
                (1, 1, 'French Fries', 'Crispy golden fries', 2.99, 'https://picsum.photos/id/3/300/200'),
                (2, 1, 'Coleslaw', 'Fresh cabbage slaw', 1.99, 'https://picsum.photos/id/4/300/200'),
                (3, 2, 'Potato Salad', 'Creamy potato salad', 2.49, 'https://picsum.photos/id/11/300/200');

            -- Drinks (IDs 1-20 reserved for sample data)
            INSERT INTO cafeteria.drink (id, location_id, drink_name, drink_description, drink_price, image_url)
            VALUES
                (1, 1, 'Coca-Cola', 'Classic Coke', 1.99, 'https://picsum.photos/id/5/300/200'),
                (2, 1, 'Lemonade', 'Fresh squeezed lemonade', 2.49, 'https://picsum.photos/id/6/300/200'),
                (3, 2, 'Iced Tea', 'Fresh brewed iced tea', 1.99, 'https://picsum.photos/id/12/300/200');

            -- Week days (IDs 1-7 for days of the week)
            INSERT INTO cafeteria.week_day (id, weekday_name)
            VALUES
                (1, 'Monday'),
                (2, 'Tuesday'),
                (3, 'Wednesday'),
                (4, 'Thursday'),
                (5, 'Friday'),
                (6, 'Saturday'),
                (7, 'Sunday');

            -- Food Options (IDs 1-20 reserved for sample data)
            INSERT INTO cafeteria.food_option (id, food_option_name, in_stock, image_url)
            VALUES
                (1, 'Lettuce', true, 'https://picsum.photos/id/7/300/200'),
                (2, 'Tomato', true, 'https://picsum.photos/id/8/300/200'),
                (3, 'Onions', true, 'https://picsum.photos/id/13/300/200');

            -- Food Option Types (IDs 1-20 reserved for sample data)
            INSERT INTO cafeteria.food_option_type (id, food_option_type_name, num_included, max_amount, food_option_price, entree_id, side_id)
            VALUES
                (1, 'Toppings', 2, 5, 0.00, 1, NULL),
                (2, 'Condiments', 2, 5, 0.00, NULL, 1);

            -- Option-Option Type relationships (IDs 1-50 reserved for sample data)
            INSERT INTO cafeteria.option_option_type (id, food_option_id, food_option_type_id)
            VALUES
                (1, 1, 1),
                (2, 2, 1),
                (3, 3, 1);

            -- Orders (IDs 1-10 reserved for sample data)
            INSERT INTO cafeteria.order (id, total_price, tax, total_swipe)
            VALUES
                (1, 12.98, 1.01, 0),
                (2, 0, 0, 1);

            -- Food Items (IDs 1-20 reserved for sample data)
            INSERT INTO cafeteria.food_item (id, name, order_id, station_id, swipe_cost, card_cost, special)
            VALUES
                (1, 'Test Entree 1', 1, 1, NULL, 8.99, false),
                (2, 'Test Side 1', 1, 1, NULL, 3.99, false),
                (3, 'Test Special', 2, 2, 1, NULL, true);

            -- Food Item Options (IDs 1-20 reserved for sample data)
            INSERT INTO cafeteria.food_item_option (id, food_item_order_id, food_option_name)
            VALUES
                (1, 1, 'Lettuce'),
                (2, 1, 'Tomato'),
                (3, 3, 'Extra Cheese');

            -- Sample customer data
            INSERT INTO cafeteria.customer (email, badger_id, first_name, last_name)
            VALUES
                ('john.doe@snow.edu', 1001234, 'John', 'Doe'),
                ('jane.smith@snow.edu', 1005678, 'Jane', 'Smith'),
                ('bob.johnson@snow.edu', 1009012, 'Bob', 'Johnson'),
                ('alice.williams@snow.edu', 1003456, 'Alice', 'Williams'),
                ('charlie.brown@snow.edu', 1007890, 'Charlie', 'Brown');

            -- Sample customer swipe data
            INSERT INTO cafeteria.customer_swipe (badger_id, swipe_balance)
            VALUES
                (1001234, 7),
                (1005678, 21),
                (1009012, 8),
                (1003456, 9),
                (1007890, 0);

            -- Set sequence start values to avoid conflicts with sample data
            SELECT setval('cafeteria.cafeteria_location_id_seq', 100, false);
            SELECT setval('cafeteria.station_id_seq', 100, false);
            SELECT setval('cafeteria.entree_id_seq', 100, false);
            SELECT setval('cafeteria.side_id_seq', 100, false);
            SELECT setval('cafeteria.drink_id_seq', 100, false);
            SELECT setval('cafeteria.food_option_id_seq', 100, false);
            SELECT setval('cafeteria.food_option_type_id_seq', 100, false);
            SELECT setval('cafeteria.option_option_type_id_seq', 100, false);
            SELECT setval('cafeteria.location_business_hours_id_seq', 100, false);
            SELECT setval('cafeteria.station_business_hours_id_seq', 100, false);
            SELECT setval('cafeteria.order_id_seq', 100, false);
            SELECT setval('cafeteria.sale_card_id_seq', 100, false);
            SELECT setval('cafeteria.sale_swipe_id_seq', 100, false);
            SELECT setval('cafeteria.food_item_id_seq', 100, false);
            SELECT setval('cafeteria.food_item_option_id_seq', 100, false);
            """;
}
