namespace Cafeteria.Api.Tests.IntegrationTests;

public static class DBSql
{
    public static readonly string SqlData = """
    CREATE SCHEMA IF NOT EXISTS cafeteria;

    CREATE TABLE
        cafeteria.cafeteria_location (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            location_name varchar(100) NOT NULL,
            location_description varchar(200) NOT NULL,
            image_url varchar(500),
            PRIMARY KEY (id)
        );

    CREATE TABLE
        cafeteria.week_day (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            weekday_name varchar(20) NOT NULL,
            PRIMARY KEY (id)
        );

    CREATE TABLE
        cafeteria.location_business_hours (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            location_id int4 NOT NULL,
            weekday_id int4 NOT NULL,
            open_time time NOT NULL,
            close_time time NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY (location_id) REFERENCES cafeteria.cafeteria_location (id),
            FOREIGN KEY (weekday_id) REFERENCES cafeteria.week_day (id)
        );


    CREATE TABLE
        cafeteria.station (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            location_id int4 NOT NULL,
            station_name varchar(50) NOT NULL,
            station_description varchar(200) NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY (location_id) REFERENCES cafeteria.cafeteria_location (id)
        );

    CREATE TABLE
        cafeteria.entree (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            station_id int4 NOT NULL,
            entree_name varchar(100) NOT NULL,
            entree_description varchar(200),
            entree_price decimal NOT NULL,
            image_url varchar(500),
            PRIMARY KEY (id),
            FOREIGN KEY (station_id) REFERENCES cafeteria.station (id)
        );

    CREATE TABLE
        cafeteria.side (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            station_id int4 NOT NULL,
            side_name varchar(100) NOT NULL,
            side_description varchar(200),
            side_price decimal NOT NULL,
            image_url varchar(500),
            PRIMARY KEY (id),
            FOREIGN KEY (station_id) REFERENCES cafeteria.station (id)
        );

    CREATE TABLE
        cafeteria.drink (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            station_id int4 NOT NULL,
            drink_name varchar(100) NOT NULL,
            drink_description varchar(200),
            drink_price decimal NOT NULL,
            image_url varchar(500),
            PRIMARY KEY (id),
            FOREIGN KEY (station_id) REFERENCES cafeteria.station (id)
        );

    CREATE TABLE
        cafeteria.meal (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            entree_id int4 NOT NULL,
            side_id int4,
            drink_id int4 NOT NULL,
            PRIMARY KEY (id),
            FOREIGN KEY (entree_id) REFERENCES cafeteria.entree (id),
            FOREIGN KEY (side_id) REFERENCES cafeteria.side (id),
            FOREIGN KEY (drink_id) REFERENCES cafeteria.drink (id)
        );

    CREATE TABLE
        cafeteria.food_option_type (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            food_option_type_name varchar(50) NOT NULL,
            num_included int2 NOT NULL,
            max_amount int4 NOT NULL,
            food_option_price decimal NOT NULL,
            entree_id int4,
            side_id int4,
            PRIMARY KEY (id)
        );

    CREATE TABLE
        cafeteria.food_option (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            food_option_name varchar(100) NOT NULL,
            in_stock boolean NOT NULL DEFAULT true,
            image_url varchar(500),
            PRIMARY KEY (id)
        );

    CREATE TABLE
        cafeteria.option_option_type (
            id int4 GENERATED BY DEFAULT AS IDENTITY,
            food_option_id int4 NOT NULL,
            food_option_type_id int4 NOT NULL,
            PRIMARY KEY (id)
        );
  """;
}